import { User, Product, Message, Conversation, Purchase } from '../types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Sarah Johnson',
    email: 'sarah@example.com',
    avatar: 'https://i.pravatar.cc/150?img=1',
    bio: 'Fashion lover and sustainable shopping advocate 🌱',
    rating: 4.8,
    totalSales: 45,
  },
  {
    id: '2',
    name: 'Emma Wilson',
    email: 'emma@example.com',
    avatar: 'https://i.pravatar.cc/150?img=5',
    bio: 'Vintage collector',
    rating: 4.9,
    totalSales: 78,
  },
  {
    id: '3',
    name: 'Michael Chen',
    email: 'michael@example.com',
    avatar: 'https://i.pravatar.cc/150?img=12',
    bio: 'Sneaker enthusiast',
    rating: 4.7,
    totalSales: 32,
  },
  {
    id: '4',
    name: 'Olivia Brown',
    email: 'olivia@example.com',
    avatar: 'https://i.pravatar.cc/150?img=9',
    bio: 'Designer bags & accessories',
    rating: 5.0,
    totalSales: 102,
  },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    title: 'Vintage Leather Jacket',
    description: 'Beautiful vintage brown leather jacket in excellent condition. Soft genuine leather with classic styling. Perfect for fall and winter.',
    price: 89.99,
    images: [
      'https://images.unsplash.com/photo-1543076447-215ad9ba6923?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkZW5pbSUyMGphY2tldHxlbnwxfHx8fDE3NjA1OTk1OTd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    category: 'Women',
    size: 'M',
    brand: 'Vintage',
    condition: 'Good',
    sellerId: '1',
    seller: mockUsers[0],
    favoriteCount: 24,
    isFavorited: false,
  },
  {
    id: '2',
    title: 'Nike Air Max Sneakers',
    description: 'Barely worn Nike Air Max in white and gray. Size 9. Only worn a few times, in like-new condition.',
    price: 65.00,
    images: [
      'https://images.unsplash.com/photo-1656944227480-98180d2a5155?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzbmVha2VycyUyMHNob2VzfGVufDF8fHx8MTc2MDY0NTgyN3ww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    category: 'Men',
    size: '9',
    brand: 'Nike',
    condition: 'Like New',
    sellerId: '3',
    seller: mockUsers[2],
    favoriteCount: 18,
    isFavorited: false,
  },
  {
    id: '3',
    title: 'Designer Handbag',
    description: 'Elegant designer handbag with gold hardware. Authentic leather, gently used. Comes with dust bag.',
    price: 145.00,
    images: [
      'https://images.unsplash.com/photo-1751522937993-46b83342398b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoYW5kYmFnJTIwcHVyc2V8ZW58MXx8fHwxNzYwNTk3MzA2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    category: 'Women',
    brand: 'Michael Kors',
    condition: 'Good',
    sellerId: '4',
    seller: mockUsers[3],
    favoriteCount: 35,
    isFavorited: true,
  },
  {
    id: '4',
    title: 'Summer Floral Dress',
    description: 'Light and breezy floral dress perfect for summer. Beautiful pattern, comfortable fit.',
    price: 35.00,
    images: [
      'https://images.unsplash.com/photo-1635447272615-a414b7ea1df4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkcmVzcyUyMGZhc2hpb258ZW58MXx8fHwxNzYwNjQ2NzA3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    category: 'Women',
    size: 'S',
    condition: 'Like New',
    sellerId: '2',
    seller: mockUsers[1],
    favoriteCount: 12,
    isFavorited: false,
  },
  {
    id: '5',
    title: 'Stylish Sunglasses',
    description: 'UV protection sunglasses with modern design. Perfect condition, barely worn.',
    price: 25.00,
    images: [
      'https://images.unsplash.com/photo-1760446032400-506ec8963e6a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdW5nbGFzc2VzJTIwYWNjZXNzb3JpZXN8ZW58MXx8fHwxNzYwNTQ3MzY4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    category: 'Accessories',
    brand: 'Ray-Ban',
    condition: 'Like New',
    sellerId: '1',
    seller: mockUsers[0],
    favoriteCount: 8,
    isFavorited: false,
  },
  {
    id: '6',
    title: 'Warm Winter Coat',
    description: 'Cozy winter coat, keeps you warm in cold weather. Great condition, no visible wear.',
    price: 78.00,
    images: [
      'https://images.unsplash.com/photo-1425100599170-85ec4f00a6ee?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3aW50ZXIlMjBjb2F0fGVufDF8fHx8MTc2MDYxOTAyM3ww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    category: 'Women',
    size: 'L',
    condition: 'Good',
    sellerId: '4',
    seller: mockUsers[3],
    favoriteCount: 16,
    isFavorited: false,
  },
  {
    id: '7',
    title: 'Classic Analog Watch',
    description: 'Elegant analog watch with leather strap. Works perfectly, minor scratches on case.',
    price: 55.00,
    images: [
      'https://images.unsplash.com/photo-1706892807280-f8648dda29ef?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3YXRjaCUyMGFjY2Vzc29yaWVzfGVufDF8fHx8MTc2MDU4NTMyMHww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    category: 'Accessories',
    brand: 'Fossil',
    condition: 'Good',
    sellerId: '3',
    seller: mockUsers[2],
    favoriteCount: 10,
    isFavorited: false,
  },
  {
    id: '8',
    title: 'Trendy Backpack',
    description: 'Modern backpack with lots of compartments. Perfect for school or daily use.',
    price: 42.00,
    images: [
      'https://images.unsplash.com/photo-1680039211156-66c721b87625?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYWNrcGFjayUyMGJhZ3xlbnwxfHx8fDE3NjA1NzEyOTB8MA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    category: 'Accessories',
    condition: 'Like New',
    sellerId: '2',
    seller: mockUsers[1],
    favoriteCount: 14,
    isFavorited: false,
  },
  {
    id: '9',
    title: 'Cozy Knit Sweater',
    description: 'Soft and comfortable knit sweater. Perfect for layering in cool weather.',
    price: 32.00,
    images: [
      'https://images.unsplash.com/photo-1631541909061-71e349d1f203?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzd2VhdGVyJTIwa25pdHdlYXJ8ZW58MXx8fHwxNzYwNjQxNjcwfDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    category: 'Women',
    size: 'M',
    condition: 'Good',
    sellerId: '1',
    seller: mockUsers[0],
    favoriteCount: 9,
    isFavorited: false,
  },
  {
    id: '10',
    title: 'Kids Rainbow Dress',
    description: 'Adorable colorful dress for kids. Size 6-7 years. Excellent condition.',
    price: 20.00,
    images: [
      'https://images.unsplash.com/photo-1622218286192-95f6a20083c7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxraWRzJTIwY2xvdGhpbmd8ZW58MXx8fHwxNzYwNjQwNjc3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    category: 'Kids',
    size: '6-7Y',
    condition: 'Like New',
    sellerId: '4',
    seller: mockUsers[3],
    favoriteCount: 6,
    isFavorited: false,
  },
  {
    id: '11',
    title: 'Minimalist Wall Art',
    description: 'Beautiful abstract wall art print. Perfect for modern home decor.',
    price: 28.00,
    images: [
      'https://images.unsplash.com/photo-1681557225327-e4e23744d667?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxob21lJTIwZGVjb3IlMjBtaW5pbWFsfGVufDF8fHx8MTc2MDU0NzY2NHww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    category: 'Home',
    condition: 'New',
    sellerId: '2',
    seller: mockUsers[1],
    favoriteCount: 11,
    isFavorited: false,
  },
  {
    id: '12',
    title: 'Vintage Fashion Collection',
    description: 'Collection of vintage fashion pieces. Unique finds from the 90s.',
    price: 125.00,
    images: [
      'https://images.unsplash.com/photo-1634133118645-74a2adf44170?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmYXNoaW9uJTIwY2xvdGhpbmclMjB2aW50YWdlfGVufDF8fHx8MTc2MDY0NjcwNXww&ixlib=rb-4.1.0&q=80&w=1080',
    ],
    category: 'Women',
    condition: 'Good',
    sellerId: '2',
    seller: mockUsers[1],
    favoriteCount: 28,
    isFavorited: true,
  },
];

export const mockMessages: Message[] = [
  {
    id: '1',
    senderId: '2',
    receiverId: '1',
    productId: '1',
    content: 'Hi! Is this jacket still available?',
    timestamp: new Date('2025-10-15T10:30:00'),
    read: true,
  },
  {
    id: '2',
    senderId: '1',
    receiverId: '2',
    productId: '1',
    content: 'Yes, it is! Would you like more photos?',
    timestamp: new Date('2025-10-15T10:45:00'),
    read: true,
  },
  {
    id: '3',
    senderId: '3',
    receiverId: '1',
    productId: '9',
    content: 'Could you measure the sweater for me?',
    timestamp: new Date('2025-10-16T09:15:00'),
    read: false,
  },
];

export const mockConversations: Conversation[] = [
  {
    id: '1',
    otherUser: mockUsers[1],
    lastMessage: mockMessages[1],
    product: mockProducts[0],
    unreadCount: 0,
  },
  {
    id: '2',
    otherUser: mockUsers[2],
    lastMessage: mockMessages[2],
    product: mockProducts[8],
    unreadCount: 1,
  },
];

export const mockPurchases: Purchase[] = [
  {
    id: '1',
    productId: '3',
    product: mockProducts[2],
    buyerId: '1',
    sellerId: '4',
    purchaseDate: new Date('2025-10-10'),
    status: 'shipped',
  },
  {
    id: '2',
    productId: '12',
    product: mockProducts[11],
    buyerId: '1',
    sellerId: '2',
    purchaseDate: new Date('2025-10-05'),
    status: 'delivered',
  },
];

// Current user (for demo purposes)
export const currentUser: User = mockUsers[0];
